export { isMajorVersionChange, diffDependencies } from './dependency-differ';
export { diffTransitive, formatTransitiveSummary } from './transitive-diff';
export { classifyChange, diffDirect, formatDirectSummary } from './direct-diff';
export { diffChangeSets, formatChangeSetSummary } from './change-set-diff';
export { buildDiffSummary, formatSummaryText, formatSummaryJson } from './summary-builder';
export { buildPatchSummary, classifyVersionChange, formatPatchSummaryText } from './patch-summary';
export { buildUpgradePath, buildUpgradePaths, formatUpgradePathText } from './upgrade-path';
export { isIgnored, applyIgnoreList, parseIgnorePatterns } from './ignored-packages';
export { compareToBaseline, exceedsDriftThreshold, formatBaselineSummary } from './baseline-comparator';
export { isExactPin, getPinnedPackages, diffPinnedPackages, formatPinnedSummaryText } from './pinned-packages';
export { classifyDriftSeverity, detectDrift, formatDriftReportText } from './drift-detector';
export { classifyOutdated, detectOutdated, formatOutdatedText } from './outdated-detector';
